#pragma once

// Generated by tools/unicode/generate.py from ICU's preparsed UCD
// (Unicode 18.0.0, ppucd.txt sha256 65ae1bd5c81539dadc37db35d04cab353bb50ee5dcf1a9eb062597f4671f9625). Do not edit.
//
// Unicode property values, in the short codes the Unicode algorithms use.

#include <cstdint>

namespace cfw::unicode {

inline constexpr const char *kUnicodeVersion = "18.0.0";

enum class GeneralCategory : std::uint8_t { Cc, Cf, Cn, Co, Cs, Ll, Lm, Lo, Lt, Lu, Mc, Me, Mn, Nd, Nl, No, Pc, Pd, Pe, Pf, Pi, Po, Ps, Sc, Sk, Sm, So, Zl, Zp, Zs };

enum class BidiClass : std::uint8_t { L, R, AL, EN, ES, ET, AN, CS, NSM, BN, B, S, WS, ON, LRE, LRO, RLE, RLO, PDF, LRI, RLI, FSI, PDI };

// UAX #14 line break classes.
enum class LineBreakClass : std::uint8_t { AI, AK, AL, AP, AS, B2, BA, BB, BK, CB, CJ, CL, CM, CP, CR, EB, EM, EX, GL, H2, H3, HH, HL, HY, ID, IN, IS, JL, JT, JV, LF, NL, NS, NU, OP, PO, PR, QU, RI, SA, SG, SP, SY, VF, VI, WJ, XX, ZW, ZWJ };

// UAX #29 grapheme cluster break values (XX = Other, CN = Control, EX = Extend, PP = Prepend,
// SM = SpacingMark; EB, EBG, EM, GAZ are unused since Unicode 11).
enum class GraphemeBreak : std::uint8_t { XX, CR, LF, CN, EX, ZWJ, RI, PP, SM, L, V, T, LV, LVT, EB, EBG, EM, GAZ };

// Indic_Conjunct_Break (UAX #29 rule GB9c).
enum class IndicConjunctBreak : std::uint8_t { None, Consonant, Extend, Linker };

// Joining_Type (Arabic, Syriac and other cursive scripts): U non-joining, C join-causing, D dual,
// L left, R right, T transparent.
enum class JoiningType : std::uint8_t { U, C, D, L, R, T };

enum class EastAsianWidth : std::uint8_t { N, A, H, F, Na, W };

// Bidi_Paired_Bracket_Type.
enum class BracketType : std::uint8_t { None, Open, Close };

// Scripts, Common, Inherited and Unknown first, then by name. iso15924() gives the four-letter code.
enum class Script : std::uint8_t {
    Common, // Zyyy
    Inherited, // Zinh
    Unknown, // Zzzz
    Adlam, // Adlm
    Afak, // Afak
    Ahom, // Ahom
    AnatolianHieroglyphs, // Hluw
    Arabic, // Arab
    Aran, // Aran
    Armenian, // Armn
    Avestan, // Avst
    Balinese, // Bali
    Bamum, // Bamu
    BassaVah, // Bass
    Batak, // Batk
    Bengali, // Beng
    BeriaErfe, // Berf
    Bhaiksuki, // Bhks
    Blis, // Blis
    Bopomofo, // Bopo
    Brahmi, // Brah
    Braille, // Brai
    Buginese, // Bugi
    Buhid, // Buhd
    CanadianAboriginal, // Cans
    Carian, // Cari
    CaucasianAlbanian, // Aghb
    Chakma, // Cakm
    Cham, // Cham
    Cherokee, // Cher
    Chorasmian, // Chrs
    Cirt, // Cirt
    Coptic, // Copt
    Cuneiform, // Xsux
    Cypriot, // Cprt
    CyproMinoan, // Cpmn
    Cyrillic, // Cyrl
    Cyrs, // Cyrs
    Deseret, // Dsrt
    Devanagari, // Deva
    DivesAkuru, // Diak
    Dogra, // Dogr
    Duployan, // Dupl
    Egyd, // Egyd
    Egyh, // Egyh
    EgyptianHieroglyphs, // Egyp
    Elbasan, // Elba
    Elymaic, // Elym
    Ethiopic, // Ethi
    Garay, // Gara
    Geok, // Geok
    Georgian, // Geor
    Glagolitic, // Glag
    Gothic, // Goth
    Grantha, // Gran
    Greek, // Grek
    Gujarati, // Gujr
    GunjalaGondi, // Gong
    Gurmukhi, // Guru
    GurungKhema, // Gukh
    Han, // Hani
    Hanb, // Hanb
    Hangul, // Hang
    HanifiRohingya, // Rohg
    Hans, // Hans
    Hant, // Hant
    Hanunoo, // Hano
    Hatran, // Hatr
    Hebrew, // Hebr
    Hiragana, // Hira
    Hntl, // Hntl
    ImperialAramaic, // Armi
    Inds, // Inds
    InscriptionalPahlavi, // Phli
    InscriptionalParthian, // Prti
    Jamo, // Jamo
    Javanese, // Java
    Jpan, // Jpan
    Jurchen, // Jurc
    Kaithi, // Kthi
    Kannada, // Knda
    Katakana, // Kana
    KatakanaOrHiragana, // Hrkt
    Kawi, // Kawi
    KayahLi, // Kali
    Kharoshthi, // Khar
    KhitanSmallScript, // Kits
    Khmer, // Khmr
    Khojki, // Khoj
    Khudawadi, // Sind
    KiratRai, // Krai
    Kore, // Kore
    Kpel, // Kpel
    Lao, // Laoo
    Latf, // Latf
    Latg, // Latg
    Latin, // Latn
    Lepcha, // Lepc
    Limbu, // Limb
    LinearA, // Lina
    LinearB, // Linb
    Lisu, // Lisu
    Loma, // Loma
    Lycian, // Lyci
    Lydian, // Lydi
    Mahajani, // Mahj
    Makasar, // Maka
    Malayalam, // Mlym
    Mandaic, // Mand
    Manichaean, // Mani
    Marchen, // Marc
    MasaramGondi, // Gonm
    Maya, // Maya
    Medefaidrin, // Medf
    MeeteiMayek, // Mtei
    MendeKikakui, // Mend
    MeroiticCursive, // Merc
    MeroiticHieroglyphs, // Mero
    Miao, // Plrd
    Modi, // Modi
    Mongolian, // Mong
    Moon, // Moon
    Mro, // Mroo
    Multani, // Mult
    Myanmar, // Mymr
    Nabataean, // Nbat
    NagMundari, // Nagm
    Nandinagari, // Nand
    NewTaiLue, // Talu
    Newa, // Newa
    Nkgb, // Nkgb
    Nko, // Nkoo
    Nushu, // Nshu
    NyiakengPuachueHmong, // Hmnp
    Ogham, // Ogam
    OlChiki, // Olck
    OlOnal, // Onao
    OldHungarian, // Hung
    OldItalic, // Ital
    OldNorthArabian, // Narb
    OldPermic, // Perm
    OldPersian, // Xpeo
    OldSogdian, // Sogo
    OldSouthArabian, // Sarb
    OldTurkic, // Orkh
    OldUyghur, // Ougr
    Oriya, // Orya
    Osage, // Osge
    Osmanya, // Osma
    PahawhHmong, // Hmng
    Palmyrene, // Palm
    PauCinHau, // Pauc
    PhagsPa, // Phag
    Phlv, // Phlv
    Phoenician, // Phnx
    ProtoCuneiform, // Pcun
    PsalterPahlavi, // Phlp
    Rejang, // Rjng
    Roro, // Roro
    Runic, // Runr
    Samaritan, // Samr
    Sara, // Sara
    Saurashtra, // Saur
    Seal, // Seal
    Sharada, // Shrd
    Shavian, // Shaw
    Siddham, // Sidd
    Sidetic, // Sidt
    SignWriting, // Sgnw
    Sinhala, // Sinh
    Sogdian, // Sogd
    SoraSompeng, // Sora
    Soyombo, // Soyo
    Sundanese, // Sund
    Sunuwar, // Sunu
    SylotiNagri, // Sylo
    Syre, // Syre
    Syriac, // Syrc
    Syrj, // Syrj
    Syrn, // Syrn
    Tagalog, // Tglg
    Tagbanwa, // Tagb
    TaiLe, // Tale
    TaiTham, // Lana
    TaiViet, // Tavt
    TaiYo, // Tayo
    Takri, // Takr
    Tamil, // Taml
    Tangsa, // Tnsa
    Tangut, // Tang
    Telugu, // Telu
    Teng, // Teng
    Thaana, // Thaa
    Thai, // Thai
    Tibetan, // Tibt
    Tifinagh, // Tfng
    Tirhuta, // Tirh
    Todhri, // Todr
    TolongSiki, // Tols
    Toto, // Toto
    TuluTigalari, // Tutg
    Ugaritic, // Ugar
    Vai, // Vaii
    Visp, // Visp
    Vithkuqi, // Vith
    Wancho, // Wcho
    WarangCiti, // Wara
    Wole, // Wole
    Yezidi, // Yezi
    Yi, // Yiii
    ZanabazarSquare, // Zanb
    Zmth, // Zmth
    Zsye, // Zsye
    Zsym, // Zsym
    Zxxx, // Zxxx
};

inline constexpr int kScriptCount = 215;

} // namespace cfw::unicode
